apiVersion: apps/v1
kind: Deployment
metadata:
  name: bol-mancala
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bol-mancala
  template:
    metadata:
      labels:
        app: bol-mancala
    spec:
      containers:
        - name: bol-mancala-image
          image: europe-central2-docker.pkg.dev/clever-form-358920/bol-mancala-repo/bol-mancala-image
