apiVersion: apps/v1
kind: Deployment
metadata:
  name: mancala-game
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mancala-game
  template:
    metadata:
      labels:
        app: mancala-game
    spec:
      containers:
        - name: mancala-game-image
          image: europe-central2-docker.pkg.dev/clever-form-358920/bol-mancala-repo/bol-mancala-image
